#  Pandas dataframes

Pandas is a module in Python. In other languages it might be called a package or a library. It is code that is not buildt into Python, but what someone else has written that we can add to our own code. 

It is a one-step process to import Python to Jupyter, but usually it is a two-step process for other programs. Here, the first step is to install the module to your computer, and the second step is to import it into our Python code. We need to import the package for each Python script we write, but only once pr. file. 

In our case, pandas is already pre-installed. Other libraries might need to be installed to be used.

We are able to make our own Python modules; Ethan will show us how if we have time on the last day of the workshop. More info in ch. 7.6 in LSP.

In [2]:
import pandas as pd #short form for pandas for ease. pd is the standard for pandas.

In [4]:
a = [3, 4, 5, 6]
b = [7, 8, 9, 10]
c = [11, 12, 13, 14]
#each list needs to have the same amount of items. this is a requirement of pandas'; it likes squares.

In [9]:
abc = pd.DataFrame({'a':a, 'b':b, 'c':c}) 
#looks like a dictionary based on syntax. ends up creating a structured overview over the data in form of a table.

In [6]:
type(abc)

pandas.DataFrame

In [7]:
abc

   a   b   c
0  3   7  11
1  4   8  12
2  5   9  13
3  6  10  14

In [11]:
#to get data out again. shows the content of 'a' along with their numbering.
abc['a']

0    3
1    4
2    5
3    6
Name: a, dtype: int64

In [12]:
d = abc['a']
type(d)

pandas.Series

In [14]:
e = list(d) #converting into list to see the numbers of a plainly, like OG a.
e

[3, 4, 5, 6]

In [16]:
a == e #== means compare these two items

True

In [17]:
abc['row_mean'] = abc.mean(axis=1)

In [18]:
abc

   a   b   c  row_mean
0  3   7  11       7.0
1  4   8  12       8.0
2  5   9  13       9.0
3  6  10  14      10.0

In [ ]:
# pretending to import csv. file
# df = pd.read_csv('/work/path') 
#df for dataframe. copy the path from the data by right clicking and selecting 'copy path'

In [19]:
df = pd.read_csv('/work/Experimental-Psycholinguistics/Stroop-raw-over-the-years.csv')

In [20]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [44]:
onlysome = df.loc[:, ['Reading_NoInt', 'Naming_Int', 'Naming_NoInt', 'Reading_Int',]] 
#you can also use onlysome = df.drop(['Year'],axis=1)

In [41]:
onlysome

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int
0             4.16        6.76          4.45         4.65
1             4.35        7.73          4.78         4.46
2             3.60        7.00          4.00         3.50
3             3.90        9.03          4.60         6.30
4             4.22        9.98          6.83         6.24
..             ...         ...           ...          ...
200           4.77       10.00          5.66         6.24
201           4.61       12.80          6.87         9.55
202           4.79       10.72          5.64         7.25
203           4.41        8.87          6.70         6.70
204           5.50        9.80          6.20        21.70

[205 rows x 4 columns]

In [42]:
onlysome['meanRT'] = onlysome.mean(axis=1)

In [43]:
onlysome

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   meanRT
0             4.16        6.76          4.45         4.65   5.0050
1             4.35        7.73          4.78         4.46   5.3300
2             3.60        7.00          4.00         3.50   4.5250
3             3.90        9.03          4.60         6.30   5.9575
4             4.22        9.98          6.83         6.24   6.8175
..             ...         ...           ...          ...      ...
200           4.77       10.00          5.66         6.24   6.6675
201           4.61       12.80          6.87         9.55   8.4575
202           4.79       10.72          5.64         7.25   7.1000
203           4.41        8.87          6.70         6.70   6.6700
204           5.50        9.80          6.20        21.70  10.8000

[205 rows x 5 columns]